name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: macos-latest
            server_artifact_name: dist/tales-server.zip
            server_asset_name: tales-server-macos-x86_64.zip
            desktop_artifact_name: dist/tales-desktop.dmg
            desktop_asset_name: tales-desktop-macos-x86_64.dmg
          - os: ubuntu-latest
            server_artifact_name: dist/tales-server.zip
            server_asset_name: tales-server-linux-x86_64.zip
            desktop_artifact_name: dist/tales-desktop.AppImage
            desktop_asset_name: tales-desktop-linux-x86_64.AppImage
          - os: windows-latest
            server_artifact_name: dist/tales-server.zip
            server_asset_name: tales-server-windows-x86_64.zip
            desktop_artifact_name: dist/tales-desktop.exe
            desktop_asset_name: tales-desktop-windows-x86_64.exe

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.3'

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

    - run: npm install

    - name: Get version from tag
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - run: make build
    - run: make dist

    - name: Upload server binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.server_artifact_name }}
        asset_name: ${{ matrix.server_asset_name }}
        tag: ${{ github.ref }}

    - name: Upload desktop binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.desktop_artifact_name }}
        asset_name: ${{ matrix.desktop_asset_name }}
        tag: ${{ github.ref }}
